blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/kako-jun/lawkit/discussions
    about: Ask questions, share ideas, or discuss lawkit with the community
  - name: 📖 Documentation
    url: https://github.com/kako-jun/lawkit/tree/main/docs
    about: Check our comprehensive documentation for usage guides and examples
  - name: 🚀 Quick Start Guide
    url: https://github.com/kako-jun/lawkit/blob/main/docs/user-guide/getting-started.md
    about: New to lawkit? Start here for installation and basic usage
  - name: 📊 Statistical Laws Reference
    url: https://github.com/kako-jun/lawkit/blob/main/docs/reference/cli-reference.md
    about: Learn about Benford's Law, Pareto Principle, Zipf's Law, and more