name: 🔒 Security Issue
description: Report a security vulnerability (privately)
title: "[Security]: "
labels: ["security", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT: Security Vulnerabilities**
        
        If you believe you've found a security vulnerability that could impact lawkit users,
        please DO NOT create a public issue. Instead, please:
        
        1. **Email us privately** at: kako.jun.42@gmail.com
        2. **Use GitHub Security Advisories**: Go to the Security tab → Report a vulnerability
        3. **Include the same information** you would provide below, but privately
        
        This form is for security-related questions and non-critical security improvements.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security concern?
      options:
        - Low (security enhancement suggestion)
        - Medium (potential security issue, not exploitable)
        - High (exploitable vulnerability - CONTACT PRIVATELY)
        - Critical (severe vulnerability - CONTACT PRIVATELY)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Concern Description
      description: Describe the security issue or enhancement suggestion
      placeholder: |
        For NON-CRITICAL issues only:
        - Security enhancement suggestions
        - Questions about security practices
        - Non-exploitable security observations
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of lawkit is affected?
      options:
        - CLI Tool (main binary)
        - npm Package (lawkit-js)
        - Python Package (lawkit-python)
        - Documentation
        - Build Process
        - Dependencies
        - Data Handling
        - Output Generation
        - All/Multiple areas
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could be the impact if this is exploited?
      placeholder: |
        This could potentially...
        Users might be affected by...
        The risk is...

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for fixing or mitigating this issue?
      placeholder: |
        This could be fixed by...
        Consider implementing...
        Recommended security practices...

  - type: input
    id: lawkit_version
    attributes:
      label: lawkit Version
      description: Run `lawkit --version`
      placeholder: "lawkit 2.1.0"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where was this observed?
      options:
        - Local development
        - Production environment
        - CI/CD pipeline
        - Container environment
        - Cloud deployment
        - Other

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: |
        Any other relevant information:
        - References to security standards
        - Similar issues in other tools
        - Compliance requirements

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: This is NOT a high/critical vulnerability (those should be reported privately)
          required: true
        - label: I have checked that this hasn't been reported before
          required: true
        - label: I understand that security issues are taken seriously
          required: true