name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Check formatting
      run: cargo fmt --all --check
      
    - name: Run Clippy
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      
    - name: Build
      run: cargo build --workspace --verbose
      
    - name: Run unit tests
      run: cargo test --workspace --lib --verbose
      
    - name: Run integration tests
      run: cargo test --workspace --test "*" --verbose
      
    - name: Test generate functionality
      run: |
        # Test basic generate functionality
        cargo run --bin lawkit -- generate benf --samples 35 --seed 12345 > /tmp/test_benf.txt
        cargo run --bin lawkit -- benf /tmp/test_benf.txt
        
        # Test generate→analyze pipeline (allow exit codes 0-12 for normal)
        cargo run --bin lawkit -- generate normal --samples 100 --mean 50 --stddev 10 --seed 42 > /tmp/test_normal.txt
        set +e
        cargo run --bin lawkit -- normal /tmp/test_normal.txt
        exit_code=$?
        set -e
        if [ $exit_code -gt 12 ]; then
          echo "Normal analysis failed with exit code $exit_code"
          exit $exit_code
        fi
        
        # Test selftest functionality
        cargo run --bin lawkit -- selftest
      
    - name: Test CLI examples from README
      run: |
        # Basic analysis examples (use --min-count to allow small datasets)
        set +e
        echo "1234 5678 9012 3456" | cargo run --bin lawkit -- benf --min-count 4
        exit_code=$?
        set -e
        if [ $exit_code -gt 12 ]; then
          echo "Benf analysis failed with exit code $exit_code"
          exit $exit_code
        fi
        
        # Generate and analyze workflow
        cargo run --bin lawkit -- generate benf --samples 100 --seed readme > /tmp/readme_test.txt
        cargo run --bin lawkit -- benf /tmp/readme_test.txt --format json
        
        # Multi-law comparison (allow exit codes 0-12 for analysis results)
        set +e
        cargo run --bin lawkit -- analyze /tmp/readme_test.txt
        exit_code=$?
        set -e
        if [ $exit_code -gt 12 ]; then
          echo "Analyze command failed with exit code $exit_code"
          exit $exit_code
        fi
        
        # List functionality
        cargo run --bin lawkit -- list